### ISSUE TITLE
Service broken on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by M0ses** [openSUSE/obs-service-bundle_gems#16]
If I try to run ```osc service lr``` in 
```
OBS:Server:Unstable/obs-server
```
it results in 

```
/usr/lib64/ruby/2.7.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'bundler' (1.17.2) required by your /home/frank/obs/OBS:Server:Unstable/obs-server/Gemfile.lock. (Gem::MissingSpecVersionError)
```
This happens because bundle_gems in TW has the shebang
 
```
#!/usr/bin/ruby.ruby2.7
```

if I change to /usr/bin/ruby.ruby2.5 it works

The service should work with multiple ruby versions

**Comment by hennevogel** [comment]
Sounds to me you want to set `%rb_default_ruby_suffix`?

https://build.opensuse.org/package/view_file/OBS:Server:Unstable/obs-service-bundle_gems/obs-service-bundle_gems.spec?expand=1

**Comment by hennevogel** [comment]
If you want to use 2.5 on tumbleweed that is.

**Comment by M0ses** [comment]
I don`t think this is a solution - just a workaround.

1. ruby 2.5 is obsolete in TW/Factory - It`s only provided by OBS:Server:Unstalbe (in my case)
2. ruby 2.7 is the current release
3. ruby 3.0 looks the upcomming new release

Which one to choose?
The service should never depend on a specific version of the interpreter/toolchain or it must be explicit (like naming the service "bundle_gems2.5", "bundle_gems2.7", etc.

**Comment by hennevogel** [comment]
> Which one to choose?

The one that is default in your build target? Which is 2.7 in our case. Unless we overwrite the default with the build variable.

Or make this runtime configurable? The we should remove the line from the spec I guess.

**Comment by M0ses** [comment]
How would you make this runtime configurable - each ruby version brings its own version of bundler - so I would guess, we would need 3 versions (ATM).

And if I understood the concept correct, each packager can choose his own preferred version of bundler in Gemfile or Gemfile.lock - correct?

**Comment by hennevogel** [comment]
> How would you make this runtime configurable

Don't depend on the versioned ruby binaries, then whichever package provides `ruby` in the path, wins. Means you can use alternatives etc.

**Comment by hennevogel** [comment]
>  each ruby version brings its own version of bundler

bundler can come from the ruby package or a rubygem package.

**Comment by hennevogel** [comment]
> And if I understood the concept correct, each packager can choose his own preferred version of bundler in Gemfile or Gemfile.lock - correct?

The version of bundler is another thing...

- gem packages are installed for a specific ruby version
- bundler itself is a gem
- bundler is creating Gemfile.lock from a Gemfile
- bundler is installing gem packages from Gemfile.lock
- Gemfile.lock "requires" a version of bundler, the one it was created with

So the problem you are seeing is:
- The shebang in the service "hardcodes" the ruby version to 2.7
- bundler is installed for 2.7 but not in the right version
- bundler is installed for ruby 2.5 in the right version
- and for this package you want to install gems for 2.5 anyway

If you remove the versioned shebang and use `/usr/bin/env ruby` then this becomes a matter of selecting the right ruby package for your build.

**Comment by M0ses** [comment]
> If you remove the versioned shebang and use `/usr/bin/env ruby` then this becomes a matter of selecting the right ruby package for your build.

But it depends on the users local settings (which preferred ruby version is selected with 'update-alternatives'), right?

It`s not up to the user, to choose - IMHO we are looking for a method were the user gets the preferred bundler version which the developer specified. Correct?

**Comment by hennevogel** [comment]
> But it depends on the users local settings (which preferred ruby version is selected with 'update-alternatives'), right?

local settings? I'm not sure I follow. Local to where? If the _service at buildtime is working or not is dependent on which ruby version is available inside the build and which one of those provides `ruby` in the path.

> It`s not up to the user, to choose - IMHO we are looking for a method were the user gets the preferred bundler version which the developer specified. Correct?

As I said, the bundler version has little to do with the version of ruby it is installed for.

**Comment by M0ses** [comment]
> > But it depends on the users local settings (which preferred ruby version is selected with 'update-alternatives'), right?
> 
> local settings? I'm not sure I follow. Local to where? 

`osc build` in `O:S:U/obs-server` on my machine for example 

> If the _service at buildtime is working or not is dependent on which ruby version is available inside the build and which one of those provides `ruby` in the path.

A service as bundle_gems _has to_ run before build time! buildtime service are isolated (without network access)!

> 
> > It`s not up to the user, to choose - IMHO we are looking for a method were the user gets the preferred bundler version which the developer specified. Correct?

> 
> As I said, the bundler version has little to do with the version of ruby it is installed for.

Nevertheless packages should be "buildable" in OBS and via `ocs build` (locally) - and local building is only possible if you have installed the matching ruby/bundler.

IMHO this is not acceptable.
